version: '3.7'

services:
  keycloak:
    image: jboss/keycloak:13.0.0
    container_name: liligpt_keycloak
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
      - "${KEYCLOAK_EXPOSE_PORT}:8080"
      - "${KEYCLOAK_EXPOSE_PORT_SSL}:8443"
      - "${KEYCLOAK_EXPOSE_PORT_WFLY}:9990"
    # volumes:
    #   # - liligpt_keycloak_data:/opt/jboss/keycloak/standalone/data
    #   # - ../../keycloak/configuration:/opt/jboss/keycloak/standalone/configuration
    networks:
      - liligpt

  db:
    image: postgres:13.2
    restart: unless-stopped
    container_name: liligpt_keycloak_db
    # ports:
    #   - "${DB_EXPOSE_PORT}:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    # volumes:
    #   - liligpt_keycloak_db:/var/lib/postgresql/data
    networks:
      - liligpt

# volumes:
#   # liligpt_keycloak_data:
#   liligpt_keycloak_db:


networks:
  liligpt:
